name: memory_app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_flux:
    git:
      url: git://github.com/google/flutter_flux
  path_provider: '^0.4.0'
  import_file:
    git:
      url: git://github.com/lucaslcode/import_file

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
