name: Memory
version: 2.0.0
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_flux:
    git:
      url: git://github.com/google/flutter_flux
  path_provider: ^0.4.0
  share: ^0.5.3
  file_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/dendrites.png"
